### ISSUE TITLE
Storing the id of the files in a mongodb schema

### ISSUE THREAD

**Issue by LSchultebraucks** [houssem-yahiaoui/fileupload-nodejs#1]
Hey, I want to  use GridFS to store files, but I want to avoid the problem of saving two files with the same name, so i want to handle the get request by id, is this possible? I would store the id then in a mongodb/mongoose schema with additional metadata. So it would probably look like this:
```
let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let schema = new Schema({
  title: { type: String, required: true },
  url: { type: String, required: true, unique: true },
  date:  { type: Date, default: Date.now },
  file_id: { type: Schema.Types.ObjectId, ref: "fs.files" }, // Storing the id of the file, which is stored in gridfs
});

module.exports = mongoose.model('blogpost', schema);
```

I don't know if I can handle this in this way. Also I do not know how then find my objects with id in my REST API. I would appreciate any kind of helpful answer :) Thanks!

Best Regards, Lasse Schultebraucks

**Comment by houssem-yahiaoui** [comment]
Okay @DarkLord44  , so regarding you schema, it's more preferable to use this format, i use it personally in my daily workflow.
When you save a file don't typically do what you're doing with file_id with the '**ref**' thing so in your upload POST request i would do something like this : 
```javascript
     let part = req.files.file;
      let mimType = fileType(part);
       let writeStream = gfs.createWriteStream({
           filename: `${req.body.rid}_translated`,
           mode: 'w',
           content_type: mimType.mime
       });
       writeStream.on('close', function (d) {
             let doc = {
                  id: d._id,
                   length: d.length,
                   name: d.filename,
                   type: d.contentType,
                    link: `https://${req.headers.host}/api/resource/reviewdoc/${d._id}`
             };
             /*
               * Then save here the doc object in your schema.
               *  In your schema you want to change the 'saved_file' type to:
               *  **_mongoose.Schema.Types.Mixed_**
              */
         });
        writeStream.write(part.data);
        writeStream.end();
```

This way you will have you file **accessible link**  with it the _id of the file so later on you can query it and deliver it and even deleting without the need to the name of the file which can be duplicated.

Hope this helps.

**Comment by DarkLord44** [comment]
I just trying this out and understanding how it works. Maybe you could a little bit more what the code does. By the way fileType is not defined, so what is the fileType?
