### ISSUE TITLE
Get All Images

### ISSUE THREAD

**Issue by oliveirawesley** [houssem-yahiaoui/fileupload-nodejs#5]
Hi Guys,

How can i list all images on a especific route for example when i call /images list all images?

Thank you very much!

**Comment by houssem-yahiaoui** [comment]
hi @oliveirawesley, for now, there's nothing as such but I'm working on revamping for the whole repo that will give you such thing.
In meantime, please consider doing it manually, meaning you create a document collection over your dB and save all uploaded documents metadata, then it will be a matter of calling for all the documents collection which will do a dB check for the files.

Hope this helps.

**Comment by houssem-yahiaoui** [comment]
@oliveirawesley please check the new Master branch where I've added this, I'm closing this issue for now if you have any inquiries please create a new one.
